version: '3.1'

services:

  front:
    image: front
    restart: always
    environment:
      PORT: 3000
    ports:
      - 3000:3000
    container_name: front


  bg:
    image: backend
    restart: always
    ports:
      - 8000:8000
    depends_on:
       front: 
          condition: service_started
    container_name: bg