version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: senha
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    container_name: banco-db


  adminer:
    image: jvdev68/todolist
    restart: always
    environment:
      USER_: user
      PASSWORD_ : password
      SECRET : muricola2930812309n8132ie
    ports:
      - 3000:3000
    depends_on:
       db: 
          condition: service_started
    container_name: adminer